[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
aya = { version = "0.13", features = ["async_tokio"] }
tokio = { version = "1.0", features = ["full"] }
pulse-common = { path = "../pulse-common", features = ["user"] }
